version: "1.0"
info:
  model: int-scaffold
packages:
- name: GitChangesTestProject
  gitServerName: test1
  gitUrl: https://github.com/Pooja-Anand-IBM-2
  gitUsername: Pooja-Anand-IBM-2
  gitBranch: main
services:
- serviceName: project.gitchangestest.integrations:e1
  packages:
  - name: GitChangesTestProject
    version: "1.0"
- serviceName: pub.date:calculateDateDifference
  packages:
  - name: WmPublic
    version: 11.1.0.0.2039
